server:
  port: 9000
spring:
  application:
    name: "catalog"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://host.docker.internal:3309/catalogdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always 
  config:
    import: "optional:configserver:http://configserver:8071/"
  # rabbitmq:
  #   host: "rabbitmq"
  #   port:  5672
  #   username: "guest"
  #   password: "guest"

services:
  inventory:
    url: http://inventory:9010

management:
  endpoints: 
    web:
      exposure: 
        include: "*"