build:
    version: "5.0"

accounts:
    message: "Welcome to account QA"
    contactDetails: 
        name:"Smith"
        email:"simth@QA"
    oncallSupport:
        -(888)234-3765
        -(999)234-3434