services:
  accounts: 
    image: bernardking08/accounts-service:s4
    container_name: account
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bernardking08
  auth: 
    image: bernardking08/auth-service:s4
    container_name: auth
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bernardking08
  catalog: 
    image: bernardking08/catalog-service:s4
    container_name: catalog
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bernardking08
  inventory: 
    image: bernardking08/inventory-service:s4
    container_name: inventory
    ports:
      - "9010:9010"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bernardking08
networks:
  bernardking08: 
    driver: "bridge"